homalg-project/homalg_project

4ti2Interface/README, ExamplesForHomalg/README, Gauss/README, GaussForHomalg/README, GradedModules/README, GradedRingForHomalg/README, HomalgToCAS/README, IO_ForHomalg/README, LocalizeRingForHomalg/README, MatricesForHomalg/README, Modules/README, PolymakeInterface/README, RingsForHomalg/README, SCO/README, ToolsForHomalg/README, ToricVarieties/README, homalg/README
The same should be done for your non-deposited packages, but I figured you could do that yourself, without me having to open a dozen pull requests... :)
=> Remove references to Netscape and .zoo from READMEs

ToolsForHomalg/gap/ToolsForHomalg.gi
Actually, on the long run I'd urge you to consider getting rid of `DeclareAttributeWithCustomGetter`, and stop abusing attributes for `MorphismAid` (the only thing using this)... :-). But that's of course a deeper change, requiring more testing, so.... :-)
=> Stop using undocumented APIs

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ToDoListEntry.gi, ToolsForHomalg/gap/ToDoLists.gd, ToolsForHomalg/gap/ToDoLists.gi
Instead of marking objects that can have a todo list,
mark objects that cannot have a todo list.
=> Reversed logic for ToDoList activation:

MatricesForHomalg/gap/LIMAT.gi, Modules/gap/GrothendieckGroup.gi
This code was accepted by GAP and silently treated as the same as in the fixed versions; but this will change in a future GAP release.
For details see <https://github.com/gap-system/gap/pull/2732>
It would be kinda cool if this fix could make it into a homalg release before GAP 4.10 is released. But of course that's not much time (a week or so), so we may just end up delaying that fix to GAP 4.11.
=> Fix use of attributes instead of their testers in method filters

.circleci/config.yml, Convex/makefile, ExamplesForHomalg/makefile, Gauss/Makefile.in, GaussForHomalg/makefile, GradedModules/makefile, GradedRingForHomalg/makefile, HomalgToCAS/makefile, IO_ForHomalg/makefile, LocalizeRingForHomalg/makefile, MatricesForHomalg/gap/HomalgRing.gd, MatricesForHomalg/makefile, Modules/makefile, RingsForHomalg/makefile, SCO/makefile, ToricVarieties/makefile, homalg/gap/HomalgComplex.gi, homalg/makefile
Display package loading info for easier debugging if a package fails to load and run tests every night.
Note: the first commit fixes tests failing with GAP 4.10.
=> Improve CI

ToricVarieties/PackageInfo.g, ToricVarieties/doc/Doc.autodoc, ToricVarieties/examples/examplesmanual/PolytopeOfDivisor.g, ToricVarieties/gap/ToricDivisors.gd
Changes are:
(1) Added PolytopeOfDivisor example, so that tests detect segmentation fault discussed in
https://github.com/homalg-project/homalg_project/issues/223
(2) Documentation builder does not support LaTeX-command "\text"
-> Removed it
(3) Updated PackageInfo.g with my current address, email, ...
=> Updated test, documentation and author information in toric varieties

MatricesForHomalg/gap/HomalgRing.gd, MatricesForHomalg/gap/HomalgRing.gi
The `/` operation accepts arbitrary strings but `HomalgRingElement`
sometimes fails if the string does not lie in `IsStringRep`.
Test case:
```
['1']/HomalgFieldOfRationalsInSingular();
```
=>  Convert strings to `IsStringRep` when coercing  if necessary

Gauss/gap/SparseMatrix.gi
This should help prevent user errors like #264, which are silently leading to wrong results, which is really bad.
The tests are really fast (linear in the number of coefficients), but if the performance of this really is a concern, then one could add a `SparseMatrixNC` without these tests. But I'd suggest to hold back with that unless it is *really* needed.
=> Validate <indices> argument to SparseMatrix constructor

MatricesForHomalg/gap/HomalgMatrix.gd
`AffineDimension` does not always return a non-negative integer as illustrated by the following example:
```
LoadPackage("RingsForHomalg");
LoadPackage("Modules");
R := HomalgFieldOfRationalsInSingular()*"x";
AffineDimension(HomalgMatrix("1", 1, 1, R));
```
=> fix the docstring for AffineDimension

MatricesForHomalg/gap/HomalgMatrix.gd
NrCols / NumberColumns is the name used by GAP >= 4.9; this
change ensures that Homalg is compliant with the MatrixObj specification.
=> Turn NrColumns into a synonym for NrCols

ToricVarieties/makedoc.g
ToricVarieties calls AutoDoc an uncommon way (at least in comparison to the other packages in the homalg_project). This leads to subtle differences in a CI environment.
=> Adjust makedoc.g to use a record instead of options

makefile
Without the indentation the error is displayed no matter which target is called (for example also when calling `make doc`). It should only be displayed for `make ci-test`.
=> Do not fail for all make targets if GAP_HOME is not set

MatricesForHomalg/doc/Matrices.xml, MatricesForHomalg/gap/Basic.gd, MatricesForHomalg/gap/Basic.gi
As far as I understand the code, if `SimplerEquivalentMatrix` gets five arguments which are all homalg matrices, the dimensions of the simpler matrix are the same as the dimensions of the input matrix.
The idea of this PR is that `homalg` provides a documented version of `SimplerEquivalentMatrix` of this particular case.
=> Add simplify for homalg matrices

Jenkinsfile
Currently Jenkins builds every branch every night and this takes about 10 hours. Thus, builds triggered in the morning will get queued and not finish until afternoon. I think it suffices to only test the master branch every night.
=> Run Jenkins cronjob only on master branch

HomalgToCAS/gap/homalgSendBlocking.gi, MatricesForHomalg/gap/HomalgMatrix.gd, MatricesForHomalg/gap/HomalgMatrix.gi, MatricesForHomalg/gap/HomalgRingRelations.gi, MatricesForHomalg/gap/Service.gi, MatricesForHomalg/gap/Tools.gi, Modules/gap/HomalgRelations.gi, Modules/gap/LIMOD.gi, Modules/gap/Modules.gi, homalg/gap/HomalgFunctor.gd, homalg/gap/HomalgFunctor.gi, homalg/gap/HomalgObject.gd, homalg/gap/StaticObjects.gi
There is also some generic code in several which uses `ResetFilterObj` on a bunch of properties and filters, e.g. in `homalgResetFilters`; this is also highly questionable and a potential source of bugs, but I see no way (for me, at least) to change that, as it digs deep into the homalg innards.
=> Fix various "abuses" of filters/properties/attributes

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/Tools.gi
before letting the generic method evalute an empty matrix,
to prevent getting the warning info:
//an empty matrix is about to get evaluated!//
=> Catching some corner cases in ConvertMatrixToRow/Column

ToricVarieties/PackageInfo.g, ToricVarieties/gap/ProjectiveToricVarieties.gd, ToricVarieties/gap/ProjectiveToricVarieties.gi
... to avoid conflicts with FinInG package which was deposited while
`ToricVarieties` was disabled.
@HereAround  Do you have any concerns about this?
=> Change the property name: IsProjectiveSpace -> IsEqualToProjectiveSpace

makefile
=> Do not build PolymakeInterface

IO_ForHomalg/gap/IO_ForHomalg.gi
This should simplify debugging, in particular if the error happens in a CI environment and cannot be reproduced easily on a local machine.
=> Display last error when CAS has died

.circleci/config.yml
This reverts commit 12e0cc5738b633c7d1ac1607489cdfa23536d4d3.
Now that GAP 4.11 is released this workaround is no longer necessary.
=> Revert "Do not upload code coverage information when testing with gap-master"

4ti2Interface/COPYING
I am afraid this also affects a bunch of other homalg-project packages, but I'd prefer if I didn't have to open PRs for each of them separately; maybe somebody who has push access to them can take care of this directly.
- Blocks
- PrimaryDecomposition
- IntrinsicCategories
- CategoriesWithAmbientObjects
- LessGenerators
- KaroubiEnvelope
- AlgebraicThomas
=> Fix phrasing in license

GradedRingForHomalg/PackageInfo.g, GradedRingForHomalg/gap/GradedRing.gd, GradedRingForHomalg/gap/GradedRing.gi
As we discussed yesterday, I have added the following adjustments to GradedRingForHomalg
* d&i IsValidRingToComputeMonomialsWithGivenDegree
* operation: MonomialsOfDegree -> key-dependent-operation: MonomialsWithGivenDegree
* add NConvex and 4ti2Interface as suggested packages
* bump version to v2020.04.16
=> The method of computing monomials of given degree in graded ring covers now more rings

RingsForHomalg/gap/SingularBasic.gi
The Singular macro
```
proc DecideZeroRows (matrix A, module B)
{
attrib(B,"isSB",1);
return(reduce(A,B));
}
```
requires `B` to be a standard basis since "The result may have no meaning if the second argument is not a standard basis." (Quote from the documentation of `reduce`).
=> Add conditions imposed on B in DecideZeroRows/Columns to documentation

RingsForHomalg/gap/Singular.gi
`redSB` does not have any influence on the specification of `lift` but slows down the computation.
This replaces https://github.com/homalg-project/homalg_project/pull/323: it gives the same performance improvement but should be much safer since it does not alter any "real" basis of rows computation.
=> Disable redSB when computing lift in BasisOfRowsCoeff (Singular)

MatricesForHomalg/gap/HomalgMatrix.gd
Happens after https://github.com/gap-system/gap/commit/52509bb9811247da6c8ed96c163572d02b6c973d
This should hopefully fix the nightly CI with gap-master.
=> Fix "method installed for DeterminantMatrix matches more than one declaration"

.circleci/config.yml, .github/workflows/ci.yml
See commit messages for details.
Regarding GitHub CI:
Pros:
* Unlimited CI minutes for public projects
* no separate login required
Cons:
* Only 2 virtual cores, so the execution time is roughly doubled compared to CircleCI
* No SSH access for debugging failing tests
In any case, this makes us more independent in case if outages etc.
=> CI improvements

MatricesForHomalg/gap/HomalgRing.gd, MatricesForHomalg/gap/HomalgRing.gi
I only deal with 2 cases:
- Integers: -> mathbb{Z}
- else: "R"
=> Add LaTeXStringOp for HomalgRings

4ti2Interface/PackageInfo.g, ExamplesForHomalg/PackageInfo.g, Gauss/PackageInfo.g, GaussForHomalg/PackageInfo.g, GradedModules/PackageInfo.g, GradedRingForHomalg/PackageInfo.g, HomalgToCAS/PackageInfo.g, IO_ForHomalg/PackageInfo.g, LocalizeRingForHomalg/PackageInfo.g, Modules/PackageInfo.g, SCO/PackageInfo.g, ToolsForHomalg/PackageInfo.g, homalg/PackageInfo.g
RingsForHomalg and MatricesForHomalg are excluded as they have a release from today.
=> Bump version of all packages and remove "Homepage update versions"

_config.yml, index.html
It has multiple advantages like telling search engines to not index the
redirecting page.
=> Use Jekyll redirect plugin

.github/workflows/Tests.yml
Currently, there is no easy way to tell if an error occurs both with `gap-stable` and `gap-master`, or only one of them, because as soon as one job fails, the other one is aborted. This PR disables this behaviour.
=> Disable fail-fast in GitHub Actions

ToolsForHomalg/gap/CachingObjects.gi
This fixes an error with the following code:
```
LoadPackage( "FinSetsForCAP" );
M := FinSet( [ 1 ] );
id := IdentityMorphism( M );
eq := Equalizer( [ id ] );
eq := fail;
GASMAN( "collect" );
emb := EmbeddingOfEqualizer( [ id ] );
```
(you have to put the code in a file and execute it to see the error, in a REPL GAP seems to keep references to `eq`).
Explanation: the call to `Equalizer` adds `eq` to `FinSets!.caches.EqualizerOp` and increments `FinSets!.caches.EqualizerOp.value_list_position` to `2`. After the garbage collection, the value is lost. Then `EmbeddingOfEqualizer` triggers a cache lookup of `EqualizerOp` during the redirect function, which decreases `FinSets!.caches.EqualizerOp.value_list_position` by one. Since the value is not found in the cache, `Equalizer( [ id ] )` is …
=> Fix caching error

4ti2Interface/PackageInfo.g, ExamplesForHomalg/PackageInfo.g, Gauss/PackageInfo.g, GaussForHomalg/PackageInfo.g, GradedModules/PackageInfo.g, GradedRingForHomalg/PackageInfo.g, HomalgToCAS/PackageInfo.g, IO_ForHomalg/PackageInfo.g, LocalizeRingForHomalg/PackageInfo.g, MatricesForHomalg/PackageInfo.g, Modules/PackageInfo.g, RingsForHomalg/PackageInfo.g, SCO/PackageInfo.g, ToolsForHomalg/PackageInfo.g, homalg/PackageInfo.g
A question @alex-konovalov: Do your GAP release scripts fetch the content of `PackageWWWHome` (and thus would possible be broken by this change, as the new URLs are redirects), or do they only care about `PackageInfoURL`, `README_URL`, etc.?
=> Use permalinks for PackageWWWHome

RingsForHomalg/gap/Singular.gi
Some of these are definitely wrong (e.g. `IsUnit`, `IsZeroMatrix`). For others, I simply did not want to dig into all the mathematics and possible Singular quirks, so better be safe than sorry and disable them.
=> Unbind some components of the homalg table of HomalgQRingOfSingular

.github/workflows/Tests.yml
Macaulay2 is missing a dependency on "install-info", so install it to make
the downgrade succeed.
=> Downgrade Macaulay2 to make the CI pass again

GradedRingForHomalg/PackageInfo.g, GradedRingForHomalg/gap/LIGrRNG.gi, RingsForHomalg/PackageInfo.g
This reverts commit dc56d8ef91e83aec47b4c82eae81faa567de85d8.
Fixes #396
=> Revert "fixed exchange of attributes for graded ring elements"

RingsForHomalg/gap/Singular.gi, RingsForHomalg/gap/SingularBasic.gi
Using the current method, `B` and `T` have to be copied twice: into the list `l`
inside the procedure and out of `homalg_variable_l` after the procedure. The
new method avoids this. This reduces peak RAM usage (and also runtime) and
fixes the "memory leak" that `homalg_variable_l` is kept alive indefinitely.
=> Return list expressions instead of lists in Singular

Modules/PackageInfo.g, Modules/gap/HomalgModule.gi
replace IsFinitelyPresentedSubmoduleRep -> IsStaticFinitelyPresentedSubobjectRep
to be able to handle homalg managed subobjects in CAP categories
=> improve ViewString for homalg modules

GradedRingForHomalg/gap/Tools.gi
Without this PR `LaTeXStringOp(e)` would fall back to `String(e)`.
=> Install LaTeXStringOp for elements of graded rings

4ti2Interface/PackageInfo.g, ExamplesForHomalg/PackageInfo.g, Gauss/PackageInfo.g, GaussForHomalg/PackageInfo.g, GradedModules/PackageInfo.g, GradedRingForHomalg/PackageInfo.g, HomalgToCAS/PackageInfo.g, IO_ForHomalg/PackageInfo.g, LocalizeRingForHomalg/PackageInfo.g, MatricesForHomalg/PackageInfo.g, Modules/PackageInfo.g, RingsForHomalg/PackageInfo.g, SCO/PackageInfo.g, ToolsForHomalg/PackageInfo.g, homalg/PackageInfo.g
Both of its uses (to control loading of the package, and of its
manuals) have been removed many years ago.
=> Remove Autoload from PackageInfo.g files

ToolsForHomalg/PackageInfo.g
I have bumped the version in 2a1069af3b854920a91875013654b15ae8123fa1 but
master already had a newer version, so no release was made.
Partially fixes https://github.com/homalg-project/CAP_project/issues/669
=> Bump version of ToolsForHomalg for new release

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/doc/Logic.xml, MatricesForHomalg/doc/Matrices.xml, MatricesForHomalg/examples/CoercedMatrix.g, MatricesForHomalg/gap/HomalgMatrix.gd, MatricesForHomalg/gap/HomalgMatrix.gi, MatricesForHomalg/gap/Tools.gi
Also see #327.
Now that `UnionOfRows` and `UnionOfColumns` get the ring as the first argument, I need more type information when coercing matrices. In particular, it is handy to have the source ring readily available. Thus, I have revived #327 with a three argument version of `CoercedMatrix`, where the first argument is the source ring. Of course, there is a convenience method where the source ring is simply obtained from the matrix.
=> Add lazy CoercedMatrix

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/Basic.gd, MatricesForHomalg/gap/Basic.gi
Those are used as attributes in CAP anyway, so turning them into attributes
on the homalg level does not change anything performance-wise, but makes
things easier for the compiler.
Note that I have simplified the `Version` in `PackageInfo.g` as discussed.
=> Turn SimplifyHomalgMatrix* into attributes

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/CachingObjects.gi
The previous behavior made all calls to `InstallMethodWithCache` after calling `InstallMethodWithCrispCache` at least once use crisp caching. This did not affect CAP operations because those are installed with their cache object explicitly.
Note: This fix might cause arbitrary performance changes if code benefits or suffers from the use of crisp caching.
=> Make sure CrispCache does not remain in options stack after calling InstallMethodWithCrispCache

.github/workflows/Tests.yml
Otherwise we trigger the error "Too many uploads to this commit".
=> Do not upload code coverage in nightly tests

GradedRingForHomalg/PackageInfo.g, GradedRingForHomalg/gap/Macaulay2Tools.gi, GradedRingForHomalg/gap/SingularTools.gi, HomalgToCAS/PackageInfo.g, HomalgToCAS/gap/IO.gi, RingsForHomalg/PackageInfo.g, RingsForHomalg/gap/Singular.gi
Relying on the order of NamesOfComponents is not safe. As a consequence, we
have to explicitly sort `superCommutative_ForHomalg` and `LinSyzForHomalg`
before `CheckLinExtSyz`.
=> Sort macros by name

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/Service.gi
Luckily, NrColumns was already set in all cases, so this did not produce
wrong results.
=> Fix wrong attribute in BasisOfColumnsCoeff

4ti2Interface/PackageInfo.g, 4ti2Interface/gap/4ti2Interface.gi
Fixes #521
Note: This might not cover all occurrences of this warning. I only made the tests pass, nothing more.
=> Ignore warnings about egrep being obsolescent coming from 4ti2

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ToolsForHomalg.gi
This reverts commit c46d85bf2cc0247737667a8271fd18b3fc101dc9.
https://github.com/gap-system/PackageDistro/pull/570 is merged, so we do not need backward compatibility anymore.
=> Revert "Restore compatibility for older versions of CAP"

HomalgToCAS/PackageInfo.g, HomalgToCAS/gap/HomalgToCAS.gi, MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/Tools.gi, RingsForHomalg/PackageInfo.g, RingsForHomalg/gap/SingularTools.gi
Currently, random matrices are created entry by entry by choosing random ring elements. Directly creating a random matrix in the CAS is much faster.
=> Speed up RandomMatrix drastically

Gauss/src/gauss.c
This helps GAP packages in Linux distros.
Also apply some cleanup
=> Gauss: #include gap_all.h instead of src/compiled.h

ci_prepare, makefile
An attempt at building the `TopcomInterface` for the ci-tests of the `homalg_project,` so that a fixed version of `topcom` is being used (cf. https://github.com/homalg-project/ToricVarieties_project/issues/200). The idea is that the installer of the `TopcomInterface` downloads and builds the version inside the folder of the `TopcomInterface` package. Ideally, the package should then find and use this very version of `topcom` (rather than e.g. the system version).
Note that this could be easily extended to the entire `ToricVarieties_project` by executing `make install` in the root folder of the `ToricVarieties_project`. I have not done this here, as it requires more build time. If this is desirable and you want to execute all tests of the `ToricVarieties_project`, this is how it could be …
=> Install TopcomInterface for ci tests

HomalgToCAS/PackageInfo.g, HomalgToCAS/gap/HomalgExternalMatrix.gi, HomalgToCAS/gap/HomalgToCAS.gd, HomalgToCAS/gap/HomalgToCAS.gi, HomalgToCAS/gap/homalgSendBlocking.gi, MatricesForHomalg/PackageInfo.g, RingsForHomalg/PackageInfo.g, RingsForHomalg/gap/Singular.gi
See commit messages for details.
4ti2Interface and IO_ForHomalg still depend on IO and use it for more intricate stuff than reading and writing files. Maybe one could also use native GAP functions there or at least make the parts really needing IO optional, but I don't plan to look into this.
Does CapAndHomalg.jl need IO_ForHomalg when talking to Singular.jl? If not, this PR allows to use Singular in CapAndHomalg.jl without IO.
=> Turn IO into a suggested dependency of HomalgToCAS

homalg/PackageInfo.g, homalg/gap/HomalgFiltration.gd, homalg/gap/HomalgSubobject.gd
I want to use `UnderlyingObject` as an attribute in `CategoryOfCospans`. Due to the lack of documentation I am not 100% sure that using it as an attribute of `IsHomalgFiltration` and `IsHomalgObject` is correct (i.e. that the underlying object of a given filtration or object does not change in the course of the computation), so please double-check.
=> Turn UnderlyingObject into an attribute

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ZFunctions.gd, ToolsForHomalg/gap/ZFunctions.gi
& bump version to v2023.02-03
(reported at https://github.com/gap-system/PackageDistro/pull/720#issuecomment-1437411538)
=> Initial(Index,Value) -> Starting(Index,Value) to avoid clashes with "InitialValue" in QPA

.github/workflows/Tests.yml, Jenkinsfile, ci_prepare
This allows to build the documentation of some packages before running the tests which prevents a race condition.
=> Clone other repos earlier

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/LazyHLists.gi
of ToolsForHomalg to V2023.05.01
=> install method for \{\}(lazy_list, list) and bump version

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ToolsForHomalg.gd, ToolsForHomalg/gap/ToolsForHomalg.gi
a version of CallFuncListWithTime which uses `Runtime` instead of `NanosecondsSinceEpoch`
=> Introduce CallFuncListWithUserTime

GradedModules/gap/BasicFunctors.gd, GradedModules/gap/BasicFunctors.gi, GradedModules/gap/GradedStructureFunctors.gd, GradedModules/gap/GradedStructureFunctors.gi, GradedModules/gap/Koszul.gd, GradedModules/gap/Koszul.gi, GradedModules/gap/OtherFunctors.gd, GradedModules/gap/OtherFunctors.gi, GradedModules/gap/ToolFunctors.gd, GradedModules/gap/ToolFunctors.gi, Modules/gap/BasicFunctors.gd, Modules/gap/BasicFunctors.gi, Modules/gap/ToolFunctors.gd, Modules/gap/ToolFunctors.gi, homalg/gap/BasicFunctors.gd, homalg/gap/BasicFunctors.gi, homalg/gap/OtherFunctors.gd, homalg/gap/OtherFunctors.gi, homalg/gap/ToolFunctors.gd, homalg/gap/ToolFunctors.gi
... in many cases. Note that `InstallValue` is a somewhat dangerous operation that we hope to phase out in GAP on the long run.
See also https://github.com/gap-system/gap/issues/1637 for some background
=> Replace InstallValue and InstallGobalFunction by BindGlobal

Gauss/PackageInfo.g
This was introduced alongside LoadKernelExtension which gauss
already uses.
=> gauss: make use of IsKernelExtensionAvailable

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/LazyHLists.gi
which is in GAP's master branch now used in MaximumList in gap/lib/list.gi
=> installed LastOp for IsLazyHListRep
