homalg-project/homalg_project

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/GenericView.gi
ViewString is the printing function used by Jupyter.
=> Install ViewString in generic view.

Gauss/PackageInfo.g, Gauss/gap/GaussDense.gd, Gauss/gap/GaussDense.gi, MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/HomalgMatrix.gd, MatricesForHomalg/gap/HomalgMatrix.gi
This was requested by @markuspf
=> Install UnionOfRows/Columns in Gauss and MatricesForHomalg

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/CachingObjects.gd, ToolsForHomalg/gap/CachingObjects.gi, ToolsForHomalg/gap/ToDoListWeakPointer.gi, ToolsForHomalg/gap/ToDoLists.gi
This should resolve all cache related problems with GAP 4.9.
=> Cache update

.circleci/config.yml, .gitignore, Convex/makefile, ExamplesForHomalg/makefile, Gauss/Makefile.in, GaussForHomalg/makefile, GradedModules/makefile, GradedRingForHomalg/makefile, HomalgToCAS/makefile, IO_ForHomalg/makefile, LocalizeRingForHomalg/makefile, MatricesForHomalg/makefile, Modules/makefile, RingsForHomalg/makefile, SCO/makefile, ToricVarieties/makefile, homalg/makefile, makefile
For an example see https://circleci.com/gh/zickgraf/homalg_project/3 and https://codecov.io/gh/zickgraf/homalg_project/tree/d7ae932b6a7886b7e3e8461944da95a556cc7ad8.
=> Add CircleCI

GradedRingForHomalg/gap/MatrixOverGradedRing.gd, GradedRingForHomalg/gap/MatrixOverGradedRing.gi
for IsMatrixOverGradedRing and IsList
the entry at position ij in the output matrix is the homogeneous part of m_ij of
degree L[i][j].
Using this method we can compute lifts and colifts in graded left/right presentations using the lifts and colifts in the non-graded case.
=> Adding a method HomogeneousPartOfMatrix( M, L )

GradedRingForHomalg/PackageInfo.g, GradedRingForHomalg/doc/MatrixOverGradedRing.xml, GradedRingForHomalg/gap/MatrixOverGradedRing.gd, GradedRingForHomalg/gap/MatrixOverGradedRing.gi
of a homalg matrix over a graded ring.
=> Implement test for homogeneity of entries

GradedRingForHomalg/doc/GradedRing.xml, GradedRingForHomalg/doc/MatrixOverGradedRing.xml, GradedRingForHomalg/gap/GradedRing.gd, GradedRingForHomalg/gap/GradedRing.gi, GradedRingForHomalg/gap/MatrixOverGradedRing.gd, GradedRingForHomalg/gap/MatrixOverGradedRing.gi
In this PR I break the previous method function of HomogeneousPartOfMatrix into two methods:
* HomogeneousPartOfRingElement,
* HomogeneousPartOfMatrix,
Of course the later uses the earlier.
Using this we can now test homogeneity of a ring element and the method @sebastianpos introduced in https://github.com/homalg-project/homalg_project/pull/240 might be a bit optimized.
=> Homogeneity and homogeneous parts of elements/matrices over graded rings

ToricVarieties/doc/Doc.autodoc
=> Use @InsertChunk instead of deprecated @InsertSystem

GradedRingForHomalg/doc/GradedRing.xml, GradedRingForHomalg/gap/GradedRing.gd
As discussed in https://github.com/homalg-project/homalg_project/issues/250.
=> Remove documentation of MatrixOfWeights

ToricVarieties/gap/ToricVarieties.gi
This closes https://github.com/homalg-project/homalg_project/issues/244.
=> Improved algorithm for SR-ideal of toric varieties

makefile
See also https://github.com/homalg-project/homalg_project/issues/277
=> Fix nightly CI

MatricesForHomalg/gap/HomalgMatrix.gd
=> Silence some warnings in GAP 4.11

ExamplesForHomalg/examples/Coupling.g, GradedModules/gap/OtherFunctors.gi, GradedRingForHomalg/gap/Tools.gi, LocalizeRingForHomalg/gap/FakeLocalizeRing.gi, LocalizeRingForHomalg/gap/LocalizeRing.gi, LocalizeRingForHomalg/gap/LocalizeRingTools.gi, MatricesForHomalg/gap/Basic.gi, MatricesForHomalg/gap/HomalgMatrix.gi, MatricesForHomalg/gap/HomalgRing.gi, MatricesForHomalg/gap/Integers.gi, MatricesForHomalg/gap/ResidueClassRingTools.gi, MatricesForHomalg/gap/Tools.gi, Modules/gap/ExteriorAlgebra.gi, Modules/gap/HomalgModule.gi, Modules/gap/Tools.gi
=> Replace some uses of MatElm and SetMatElm 

.circleci/config.yml, .gitignore, Convex/makefile, ExamplesForHomalg/examples/MAGMA/update, ExamplesForHomalg/examples/Macaulay2/update, ExamplesForHomalg/examples/maple/update, ExamplesForHomalg/makefile, Gauss/Makefile.in, GaussForHomalg/makefile, GradedModules/examples/MAGMA/update, GradedModules/examples/Macaulay2/update, GradedModules/examples/maple/update, GradedModules/makefile, GradedRingForHomalg/makefile, HomalgToCAS/makefile, IO_ForHomalg/makefile, Jenkinsfile, LocalizeRingForHomalg/makefile, MatricesForHomalg/makefile, Modules/makefile, RingsForHomalg/makefile, SCO/makefile, ToricVarieties/makefile, ci_prepare, gather_performance_data.py, homalg/makefile, makefile
This depends on homalg-project/alexander#3 and homalg-project/VirtualCAS#3.
=> Add test_suite and Jenkins to CI

makefile
=> Disable tests failing with gap-master

.gitignore, Convex/makefile, ExamplesForHomalg/makefile, Gauss/Makefile.in, GaussForHomalg/makefile, GradedModules/makefile, GradedRingForHomalg/makefile, HomalgToCAS/makefile, IO_ForHomalg/makefile, Jenkinsfile, LocalizeRingForHomalg/makefile, MatricesForHomalg/makefile, Modules/makefile, RingsForHomalg/makefile, SCO/makefile, ToricVarieties/makefile, gather_performance_data.py, homalg/makefile, makefile
Note: I have adapted `alexander`, `D-Modules`, `Sheaves` and `VirtualCAS` for this PR by pushing directly to their master branches.
=> Plot every test in a different plot and plot both cpu and real time

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/doc/Matrices.xml, MatricesForHomalg/gap/Basic.gd, MatricesForHomalg/gap/Basic.gi
for homalg matrices in the case where a reduced echelon form is available.
=> One sided simplification

MatricesForHomalg/gap/ResidueClassRingTools.gi
Fixup of 7282a1bcc64865cb4844277a18e0e75b80a26c2e
Fixes #302
=> TransposedMat -> TransposedMatrix

Gauss/gap/SparseMatrix.gd, Gauss/gap/SparseMatrix.gi, Gauss/gap/SparseMatrixGF2.gi
* IsRowOfSparseMatrix
* LatexStringSparseMatrixGF2
provided via email from Madeleine Whybrow (@MWhybrow92).
=> Added two methods in Gauss

ExamplesForHomalg/PackageInfo.g, GaussForHomalg/PackageInfo.g, GaussForHomalg/doc/methods.xml, GaussForHomalg/gap/GaussRationals.gd, GaussForHomalg/gap/GaussRationals.gi, GaussForHomalg/gap/GaussTools.gd, GaussForHomalg/gap/GaussTools.gi, GaussForHomalg/init.g, MatricesForHomalg/PackageInfo.g, MatricesForHomalg/doc/Rings.xml, MatricesForHomalg/gap/HomalgRing.gd, MatricesForHomalg/gap/HomalgRing.gi, MatricesForHomalg/gap/Tools.gd, Modules/PackageInfo.g, RingsForHomalg/PackageInfo.g, RingsForHomalg/gap/GAPHomalg.gi
* Part of the integer constructor that deals with
Z/p^nZ
* Rational constructor
Resolves #147
=> Moved ring constructors from Matrices to Gauss:

HomalgToCAS/gap/HomalgExternalRing.gi
All other installations of RingMap seem to delegate to this installation.
Fixes #270.
=> Add sanity check to RingMap

RingsForHomalg/examples/RingConstructionsSingular.g, RingsForHomalg/gap/Singular.gd, RingsForHomalg/gap/Singular.gi
Add ability to use Singular qrings from homalg. I have not tested this extensively but did not encounter any issues in my applications.
=> Add HomalgQRingInSingular

README_DEV.md
containing some instructions for developers/contributors.
=> Add README_DEV.md

README_DEV.md
@HereAround These improvements are based on your questions. If you have ideas for further improvements, clarifications, etc., feel free to create a PR.
=> Improve README_DEV.md

Jenkinsfile, ci_prepare, makefile
@zickgraf - please review these changes.
=> Add ToricVarieties to test_suite

4ti2Interface/PackageInfo.g, 4ti2Interface/gap/4ti2Interface.gi
closes #homalg-project/homalg_project/issues/345
=> issue fix in 4ti2Interface

.circleci/config.yml, .github/workflows/Tests.yml
Also apply some further changes from PackageJanitor
See https://github.com/homalg-project/CAP_project/pull/574 for explanation
=> Only run CI on master branch and branches ending with "-ci"

MatricesForHomalg/gap/HomalgRing.gi
- field of rationals
- finite fields of prime order
=> Install LaTeXStringOp for some homalg fields:

4ti2Interface/README.md, ExamplesForHomalg/README.md, Gauss/README.md, GaussForHomalg/README.md, GradedModules/README.md, GradedRingForHomalg/README.md, HomalgToCAS/README.md, IO_ForHomalg/README.md, LocalizeRingForHomalg/README.md, MatricesForHomalg/README.md, Modules/README.md, README.md, RingsForHomalg/README.md, SCO/README.md, ToolsForHomalg/README.md, homalg/README.md
You can view the result here: https://github.com/zickgraf/homalg_project/tree/PackageJanitor
=> Apply PackageJanitor

4ti2Interface/badge_date.json, 4ti2Interface/badge_version.json, ExamplesForHomalg/badge_date.json, ExamplesForHomalg/badge_version.json, Gauss/badge_date.json, Gauss/badge_version.json, GaussForHomalg/badge_date.json, GaussForHomalg/badge_version.json, GradedModules/badge_date.json, GradedModules/badge_version.json, GradedRingForHomalg/badge_date.json, GradedRingForHomalg/badge_version.json, HomalgToCAS/badge_date.json, HomalgToCAS/badge_version.json, IO_ForHomalg/badge_date.json, IO_ForHomalg/badge_version.json, LocalizeRingForHomalg/badge_date.json, LocalizeRingForHomalg/badge_version.json, MatricesForHomalg/badge_date.json, MatricesForHomalg/badge_version.json, Modules/badge_date.json, Modules/badge_version.json, RingsForHomalg/badge_date.json, RingsForHomalg/badge_version.json, SCO/badge_date.json, SCO/badge_version.json, ToolsForHomalg/badge_date.json, ToolsForHomalg/badge_version.json, homalg/badge_date.json, homalg/badge_version.json
Merge #382 first (yes, this time the gh-pages branch has to be merged AFTER the master branch).
=> Apply PackageJanitor to gh-pages

GradedRingForHomalg/PackageInfo.g, GradedRingForHomalg/gap/Tools.gi
* DegreeOfRingElementFunction
* DegreesOfEntriesFunction
* NonTrivialDegreePerRowWithColPositionFunction
* NonTrivialDegreePerColumnWithRowPositionFunction
=> fixed degree helper functions to work even if ring table entries are not bound

Modules/PackageInfo.g, Modules/gap/Modules.gi
=> fixed PushPresentationByIsomorphism for right modules

RingsForHomalg/PackageInfo.g, RingsForHomalg/gap/Singular.gi
It should work as expected. Of course one has to make sure that the map
actually defines a homomorphism.
=> Reenable Pullback for HomalgQRingInSingular

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/HomalgRing.gi
For example, this is used by RingAsCategory.
=> Add ViewString for IsHomalgRingElement

Modules/PackageInfo.g, Modules/gap/HomalgModule.gi
from IsFinitelyPresentedModuleRep -> IsHomalgModule
in order to use it for displaying graded modules
in the package IntrinsicGradedModules
=> weaken filter for Display( M, "" )

Modules/gap/HomalgModule.gi
from IsFinitelyPresentedModuleRep -> IsHomalgModule
in order to use it for displaying graded modules
in the package IntrinsicGradedModules
=> weaken filter for ViewString

Modules/PackageInfo.g, Modules/gap/HomalgModule.gi
provided the ring HasInvariantBasisProperty( R )
=> SetRankOfObject( M, NrGenerators( M ) ) if NrRelations( M ) = 0

GradedModules/PackageInfo.g, GradedModules/gap/GradedModule.gi, GradedRingForHomalg/PackageInfo.g, GradedRingForHomalg/gap/MatrixOverGradedRing.gd, GradedRingForHomalg/gap/MatrixOverGradedRing.gi
and simplified MonomialMap using it
=> d&i MonomialMatrix for more arguments

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ToolsForHomalg.gd, ToolsForHomalg/gap/ToolsForHomalg.gi
I want to use those functions to automatically generate files in CAP.
=> Add various functions to read from / write to files

Modules/PackageInfo.g, Modules/gap/HomalgMap.gi
when using IntrinsicModules we would otherwise run into
an equaly strong method which currently raises an error
=> added a higher priority method for HomalgMap

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/Service.gd
=> check if RowEchelonForm is bound

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ToolsForHomalg.gd, ToolsForHomalg/gap/ToolsForHomalg.gi
=> Add ReplacedStringViaRecord

RingsForHomalg/PackageInfo.g, RingsForHomalg/gap/Singular.gi
Fixes #441
See Hans' answer https://github.com/Singular/Singular/issues/1101#issuecomment-859310345
=> Do not use Singular's nres over the integers

RingsForHomalg/PackageInfo.g, RingsForHomalg/gap/Singular.gi
by adding missing code as in PolynomialRing
Fixes #370
=> fixed HomalgRingOfIntegersInSingular

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/doc/Matrices.xml, MatricesForHomalg/gap/HomalgMatrix.gd, MatricesForHomalg/gap/HomalgMatrix.gi
This provides type information for CompilerForCAP.
=> Add HomalgMatrixListList

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ToolsForHomalg.gd, ToolsForHomalg/gap/ToolsForHomalg.gi
These allow to easily measure the time spent in a certain portion of the
code:
```
gap> StartTimer( "MyTimer" );
gap> ... some code ...
gap> StopTimer( "MyTimer" );
```
and later
```
gap> DisplayTimer( "MyTimer" );
Timer MyTimer (stopped): started 2 times with a total runtime of 2 ms ( = 1000 μs per run)
```
=> Add the commands StartTimer, StopTimer, and DisplayTimer

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/Tools.gi
addresses https://github.com/homalg-project/homalg_project/issues/465#issuecomment-1066865080
=> don't issue a warning if `utils` is not loaded

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ToolsForHomalg.gi
This should address the issue in https://github.com/homalg-project/Toposes/issues/26.
=> WriteReplacedFileForHomalg: put `header` below the default file header

.github/workflows/Tests.yml
See https://github.com/homalg-project/homalg_project/issues/456#issuecomment-1108503204.
=> Do not downgrade macaulay2 and rely on preinstalled "time"

process_coverage.py
This should hopefully fix the recent code coverage drop.
=> Also process coverage files of tested packages outside of homalg_project

IO_ForHomalg/PackageInfo.g, IO_ForHomalg/gap/IO_ForHomalg.gd, IO_ForHomalg/gap/IO_ForHomalg.gi, RingsForHomalg/PackageInfo.g, RingsForHomalg/examples/RingConstructionsMAGMA.g, RingsForHomalg/examples/RingConstructionsMacaulay2.g, RingsForHomalg/examples/RingConstructionsMaple.g, RingsForHomalg/examples/RingConstructionsSage.g, RingsForHomalg/examples/RingConstructionsSingular.g, makefile
Addresses https://github.com/homalg-project/homalg_project/issues/487#issuecomment-1218738083
=> Run tests conditionally only if required executables are available

ExamplesForHomalg/PackageInfo.g, ExamplesForHomalg/examples/ReflexiveNonProjectiveIdeal.g
This together with https://github.com/homalg-project/alcove/pull/2 should fix the CI.
=> Fix wrong usage of Assert

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/LazyArrays.gd, ToolsForHomalg/gap/LazyHLists.gd, ToolsForHomalg/gap/LazyHLists.gi, ToolsForHomalg/init.g, ToolsForHomalg/read.g
avoid name collision with hap reported in:
https://github.com/gap-system/PackageDistro/pull/533#issuecomment-1236429412
=> renamed LazyList -> LazyHList (lazy homogeneous list)

ci_prepare, makefile
Running these tests simply increases the runtime of the CI without any benefit.
=> Remove ignored tests

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/Tools.gi
=> Handle empty matrices in RandomMatrix explicitly

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/Tools.gi
See the commit message for details.
=> Get simpler random matrices/elements by adjusting the current hard coded parameters

GradedRingForHomalg/PackageInfo.g, GradedRingForHomalg/gap/LIGrRNG.gd, GradedRingForHomalg/gap/LIGrRNG.gi, GradedRingForHomalg/gap/MatrixOverGradedRing.gd, GradedRingForHomalg/gap/MatrixOverGradedRing.gi
and bump version to 2022.10.01
=> Add random methods to homalg graded rings

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/LIMAT.gi
Fixes https://github.com/homalg-project/CAP_project/issues/1115.
=> Call DiagMat with the ring as first argument to handle the empty case

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ToolsForHomalg.gi
and clean up other dependencies
=> Avoid dependency of ToolsForHomalg on IO

Gauss/PackageInfo.g, Gauss/examples/.gitkeep, HomalgToCAS/PackageInfo.g, HomalgToCAS/examples/.gitkeep, IO_ForHomalg/PackageInfo.g, IO_ForHomalg/examples/.gitkeep
=> Add motivation to .gitkeep files

MatricesForHomalg/PackageInfo.g, MatricesForHomalg/gap/HomalgMatrix.gd, MatricesForHomalg/gap/HomalgMatrix.gi, MatricesForHomalg/tst/EntriesOfHomalgRowVector.tst
This allows to have more semantics than EntriesOfHomalgMatrix for CompilerForCAP.
=> Add EntriesOfHomalgRowVector and EntriesOfHomalgColumnVector

Gauss/PackageInfo.g, Gauss/src/gauss.c
resolves https://github.com/homalg-project/homalg_project/issues/560
=> fix segfault as suggested by @ChrisJefferson

homalg/PackageInfo.g, homalg/gap/HomalgFiltration.gd, homalg/gap/HomalgSubobject.gd
Reverts homalg-project/homalg_project#563
See #564.
=> Revert "Turn UnderlyingObject into an attribute"

Gauss/src/gauss.c, Gauss/tst/sparsematrix.tst
This fixes ranges being used in SparseMatrix, and adds some basic tests for SparseMatrix
=> Fix handling ranges in SparseMatrix

4ti2Interface/PackageInfo.g, 4ti2Interface/gap/4ti2Interface.gi
resolves https://github.com/homalg-project/homalg_project/issues/568
=> resolved issue #568

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/examples/ZFunctionWithInductiveSides.g, ToolsForHomalg/gap/ZFunctions.gd, ToolsForHomalg/gap/ZFunctions.gi, ToolsForHomalg/init.g, ToolsForHomalg/read.g
and bump version to v2023.02-01
=> move ZFunctions from ToolsForHigherHomologicalAlgebra to ToolsForHomalg

ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/GenericView.gd, ToolsForHomalg/gap/GenericView.gi
and rely on GAP's generic derivation of ViewObj from ViewString and Display from DisplayString
=> Only install string methods in InstallPrintFunctionsOutOfPrintingGraph

makefile
See https://github.com/homalg-project/ToricVarieties_project/issues/205
=> Disable tests of ToricVarieties due to segfaults

ExamplesForHomalg/PackageInfo.g, ExamplesForHomalg/examples/Oscar/ReducedBasisOfModule.g, ToolsForHomalg/PackageInfo.g, ToolsForHomalg/gap/ToolsForHomalg.gd, ToolsForHomalg/gap/ToolsForHomalg.gi
following suggestion in https://github.com/homalg-project/CAP_project/pull/1356#pullrequestreview-1509534423
=> ListImpliedFilters now includes the filter itself

RingsForHomalg/PackageInfo.g, RingsForHomalg/gap/SingularTools.gi
following suggestion in https://github.com/Singular/Singular/issues/1227#issuecomment-2180674525
=> fixed CoefficientsOfUnreducedNumeratorOfHilbertPoincareSeries
